const images = {
  LOGO_HOME: require('./img/HomeIcon.png'),
  LOGO_MAGAZINE: require('./img/MagazineIcon.png'),
  LOGO_MY: require('./img/MyIcon.png'),
  LOGO_BLACK: require('./img/logo_black.png'),
  WARNING_CIRCLE: require('./img/WarningCircle.png'),
  LEFT_ICON: require('./img/CaretLeft.png'),
  RIGHT_ICON: require('./img/rightIcon.png'),
  BOOKMARK_ICON: require('./img/BookmarkSimple.png'),
  BOOKMARK_YELLOW_ICON: require('./img/BookmarkYellow.png'),
  PENCIL_ICON: require('./img/pencil.png'),
  PROFILE_WHITE: require('./img/profileImg.png'),
  PROFILE_GRAY: require('./img/ProfileImg2.png'),
  LOGO: require('./img/logo.png'),
  X: require('./img/X.png'),
  DOTSTHREEOUTLINEVERTICAL: require('./img/DotsThreeOutlineVertical.png'),
  BOOKMARK_GRAY: require('./img/BookmarkGray.png'),
  HEADER_LOGO: require('./img/HeaderLogo.png'),
  BELL: require('./img/Bell.png'),
  CONTACT_FREE_MEETING: require('./img/contact_free_meeting.png'),
  CONTACT_MEETING: require('./img/contact_meeting.png'),
  LAPTOP_WORK: require('./img/laptop_work.png'),
  PERSONAL_STUDY: require('./img/personal_study.png'),
  SAMPLE_PLACE_IMAGE: require('./img/sample_place_image.png'),
  SPARKLE: require('./img/Sparkle.png'),
  GRAY_LOGO: require('./img/grayLogo.png'),
  BLACK_LOGO: require('./img/blackLogo.png'),
  MAGAZINE_1: require('./img/magazine_1.png'),
  MAGAZINE_2: require('./img/magazine_2.png'),
  MAGAZINE_3: require('./img/magazine_3.png'),
  MAGAZINE_4: require('./img/magazine_4.png'),
  MAGAZINE_5: require('./img/magazine_5.png'),
  MAGAZINE_6: require('./img/magazine_6.png'),
  SPONSOR_1: require('./img/sponsor_1st_image.png'),
  SPONSOR_2: require('./img/sponsor_2nd_image.png'),
};

export default images;
